### ISSUE TITLE
Access to processed dataset

### ISSUE THREAD

**Issue by abalhomaid** [runnanchen/Anatomic-Landmark-Detection#4]
Hello,

Many thanks for the hard work put in the paper and code.

Would it be possible for me to have access to the drive to download the processed dataset, please? 
I am unauthorized to do so currently as shown in the below image

![image](https://github.com/runnanchen/Anatomic-Landmark-Detection/assets/12021070/be607b9b-7cc0-44ff-9b12-17690939877e)

Thank you

**Comment by Xushuolin** [comment]
me too

**Comment by 5k5000** [comment]
@runnanchen  Hello, Could you please fix this problem？ It seems that the performance greatly depends on the preprocessed dataset.

**Comment by runnanchen** [comment]
The problem has been fixed. Thanks!

**Comment by yeyuxmf** [comment]
@runnanchen I still don't have permission to access sharepoint's address. Unable to obtain your preprocessed data.

**Comment by NavinAananthan** [comment]
I couldn't access the preprocessed dataset it showing as below 
![image](https://github.com/runnanchen/Anatomic-Landmark-Detection/assets/81963819/2beda6cd-2cca-45f7-8c67-1bcb2149ee85)
